import type {
  User, ContributorProfile, BusinessProfile,
  Task, Submission, Wallet, LeaderboardEntry,
  Notification, BusinessAnalytics
} from '../types/models';

// ============================
// Demo Users
// ============================

export const DEMO_CONTRIBUTOR_USER: User = {
  id: 'user-contributor-demo',
  email: 'parth@taskproof.dev',
  name: 'Parth Sharma',
  role: 'contributor',
  avatar: undefined,
  createdAt: '2026-07-15T10:00:00Z',
};

export const DEMO_BUSINESS_USER: User = {
  id: 'user-business-demo',
  email: 'admin@techcorp.com',
  name: 'TechCorp Admin',
  role: 'business',
  avatar: undefined,
  createdAt: '2026-06-01T09:00:00Z',
};

// ============================
// Contributor Profile
// ============================

export const DEMO_CONTRIBUTOR_PROFILE: ContributorProfile = {
  userId: 'user-contributor-demo',
  username: 'parth_s',
  bio: 'Computer Science student passionate about AI and data science.',
  college: 'IIT Bombay',
  skills: ['Data Labeling', 'AI Evaluation', 'Research', 'Content Review', 'Testing'],
  level: 4,
  levelName: 'Data Explorer',
  xp: 2340,
  xpToNextLevel: 3000,
  streak: 5,
  tasksCompleted: 48,
  qualityScore: 96,
  rating: 4.8,
  totalEarned: 1250,
  walletAddress: '0xA3f8...3D2c',
  badges: [
    { id: 'b1', name: 'First Task', description: 'Completed your first task', icon: 'Star', earnedAt: '2026-07-16T12:00:00Z', rarity: 'common' },
    { id: 'b2', name: '7 Day Streak', description: '7 consecutive days of tasks', icon: 'Flame', earnedAt: '2026-07-25T12:00:00Z', rarity: 'uncommon' },
    { id: 'b3', name: 'Top Contributor', description: 'Ranked in top 10 this week', icon: 'Trophy', earnedAt: '2026-08-10T12:00:00Z', rarity: 'rare' },
    { id: 'b4', name: 'Explorer', description: 'Completed tasks in 3+ categories', icon: 'Compass', earnedAt: '2026-08-20T12:00:00Z', rarity: 'uncommon' },
    { id: 'b5', name: 'Verified Pro', description: '95%+ quality score over 30 tasks', icon: 'ShieldCheck', earnedAt: '2026-09-01T12:00:00Z', rarity: 'rare' },
  ],
  joinedAt: '2026-07-15T10:00:00Z',
};

// ============================
// Business Profile
// ============================

export const DEMO_BUSINESS_PROFILE: BusinessProfile = {
  userId: 'user-business-demo',
  companyName: 'TechCorp',
  industry: 'Technology / AI',
  website: 'https://techcorp.example.com',
  tasksCreated: 12,
  totalSpent: 8450,
  approvalRate: 87,
  joinedAt: '2026-06-01T09:00:00Z',
};

// ============================
// Tasks
// ============================

export const SEED_TASKS: Task[] = [
  {
    id: 'task-001',
    title: 'Product Image Categorization',
    category: 'data-labeling',
    shortDescription: 'Categorize product images into the correct e-commerce categories.',
    description: 'You will be shown 10 product images from our e-commerce dataset. Assign the correct top-level category and sub-category to each product. Accurate labeling helps train our recommendation engine.',
    reward: 50,
    estimatedMinutes: 12,
    difficulty: 'easy',
    slots: 200,
    remainingSlots: 124,
    qualityScore: 98,
    status: 'active',
    businessId: 'user-business-demo',
    businessName: 'TechCorp',
    tags: ['images', 'e-commerce', 'labeling'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Select one primary category per image.' },
      { id: 'r2', type: 'instruction', description: 'Use "Unknown" only if the product cannot be identified.' },
      { id: 'r3', type: 'instruction', description: 'Complete all 10 images before submitting.' },
      { id: 'r4', type: 'acceptance_criteria', description: 'At least 9/10 categories must match the gold standard.' },
      { id: 'r5', type: 'acceptance_criteria', description: 'No blank or placeholder entries accepted.' },
      { id: 'r6', type: 'example', description: 'A photo of running shoes → Category: Footwear > Athletic Shoes' },
    ],
    inputFields: [
      { id: 'f1', label: 'Product Category', type: 'select', options: ['Electronics', 'Footwear', 'Clothing', 'Home & Garden', 'Toys', 'Books', 'Food & Beverage', 'Beauty', 'Sports', 'Unknown'], required: true },
      { id: 'f2', label: 'Confidence Level', type: 'radio', options: ['High', 'Medium', 'Low'], required: true },
      { id: 'f3', label: 'Notes (optional)', type: 'textarea', required: false, placeholder: 'Any observations about this image...' },
    ],
    createdAt: '2026-09-20T09:00:00Z',
    expiresAt: '2026-11-01T00:00:00Z',
  },
  {
    id: 'task-002',
    title: 'AI Response Evaluation',
    category: 'ai-evaluation',
    shortDescription: 'Rate AI-generated responses for quality, accuracy, and helpfulness.',
    description: 'Evaluate responses generated by an AI assistant. You will see a question and two AI-generated answers. Rate each answer on accuracy, helpfulness, and tone. This data is used to improve AI alignment and response quality.',
    reward: 35,
    estimatedMinutes: 7,
    difficulty: 'medium',
    slots: 500,
    remainingSlots: 312,
    qualityScore: 95,
    status: 'active',
    businessId: 'biz-nova-labs',
    businessName: 'Nova Labs',
    tags: ['AI', 'evaluation', 'NLP'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Read both AI responses carefully before rating.' },
      { id: 'r2', type: 'instruction', description: 'Rate independently — do not let the order influence you.' },
      { id: 'r3', type: 'acceptance_criteria', description: 'All rating fields must be filled.' },
      { id: 'r4', type: 'acceptance_criteria', description: 'Justification required if rating is 1 or 5.' },
      { id: 'r5', type: 'example', description: 'If Response A is factually wrong, rate Accuracy: 1/5.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Better Response', type: 'radio', options: ['Response A', 'Response B', 'Both Equal', 'Both Poor'], required: true },
      { id: 'f2', label: 'Accuracy (1–5)', type: 'rating', options: ['1','2','3','4','5'], required: true },
      { id: 'f3', label: 'Helpfulness (1–5)', type: 'rating', options: ['1','2','3','4','5'], required: true },
      { id: 'f4', label: 'Tone (1–5)', type: 'rating', options: ['1','2','3','4','5'], required: true },
      { id: 'f5', label: 'Brief Justification', type: 'textarea', required: false, placeholder: 'Why did you choose this rating?' },
    ],
    createdAt: '2026-09-22T11:00:00Z',
  },
  {
    id: 'task-003',
    title: 'Website UX Testing',
    category: 'testing',
    shortDescription: 'Test a web app and report usability issues with structured feedback.',
    description: 'Perform structured usability testing on our new dashboard product. Follow the test script to complete 5 specific user flows and document any friction, confusion, or broken interactions you encounter.',
    reward: 70,
    estimatedMinutes: 18,
    difficulty: 'medium',
    slots: 80,
    remainingSlots: 43,
    qualityScore: 97,
    status: 'active',
    businessId: 'biz-datanest',
    businessName: 'DataNest',
    tags: ['UX', 'testing', 'usability'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Use Chrome or Firefox (latest version).' },
      { id: 'r2', type: 'instruction', description: 'Complete all 5 test flows before submitting.' },
      { id: 'r3', type: 'acceptance_criteria', description: 'Each flow report must have at least one observation.' },
      { id: 'r4', type: 'acceptance_criteria', description: 'Screenshots or descriptions must be specific — no vague feedback.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Overall Usability (1–10)', type: 'rating', options: ['1','2','3','4','5','6','7','8','9','10'], required: true },
      { id: 'f2', label: 'Navigation Issues Found', type: 'textarea', required: true, placeholder: 'Describe any navigation problems...' },
      { id: 'f3', label: 'Broken or Confusing UI Elements', type: 'textarea', required: true, placeholder: 'Describe specific UI issues...' },
      { id: 'f4', label: 'Task Completion', type: 'radio', options: ['All 5 flows completed', '4 flows completed', '3 or fewer flows completed'], required: true },
    ],
    createdAt: '2026-09-25T14:00:00Z',
  },
  {
    id: 'task-004',
    title: 'Survey on Student Tech Habits',
    category: 'survey',
    shortDescription: 'Share your experience with digital tools as a student.',
    description: 'Participate in a structured research survey on how students use digital tools for studying, collaboration, and career building. Your responses will feed into an academic research paper on EdTech adoption.',
    reward: 20,
    estimatedMinutes: 5,
    difficulty: 'easy',
    slots: 1000,
    remainingSlots: 687,
    qualityScore: 99,
    status: 'active',
    businessId: 'biz-urban-research',
    businessName: 'Urban Research',
    tags: ['survey', 'education', 'research'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Must be a current student or recent graduate (last 2 years).' },
      { id: 'r2', type: 'acceptance_criteria', description: 'All required questions must be answered.' },
      { id: 'r3', type: 'acceptance_criteria', description: 'Text answers must be at least 2 sentences.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Primary Learning Tool', type: 'select', options: ['YouTube', 'Coursera/MOOC', 'University LMS', 'Textbooks', 'Peer study groups', 'Other'], required: true },
      { id: 'f2', label: 'Hours per week spent on digital learning', type: 'radio', options: ['0–2 hours', '3–5 hours', '6–10 hours', '10+ hours'], required: true },
      { id: 'f3', label: 'Biggest challenge with online learning', type: 'textarea', required: true, placeholder: 'Describe in 2+ sentences...' },
      { id: 'f4', label: 'Tools you wish existed', type: 'textarea', required: false, placeholder: 'Optional: any tools you wish existed for learning?' },
    ],
    createdAt: '2026-09-28T08:00:00Z',
  },
  {
    id: 'task-005',
    title: 'Product Description Review',
    category: 'content-review',
    shortDescription: 'Review AI-generated product descriptions for quality and accuracy.',
    description: 'Review 5 AI-generated product descriptions and rate them for accuracy, readability, and brand voice. Flag any descriptions that contain factual errors, grammatical issues, or misleading information.',
    reward: 40,
    estimatedMinutes: 10,
    difficulty: 'easy',
    slots: 150,
    remainingSlots: 89,
    qualityScore: 96,
    status: 'active',
    businessId: 'user-business-demo',
    businessName: 'TechCorp',
    tags: ['content', 'review', 'writing'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Read each description fully before rating.' },
      { id: 'r2', type: 'acceptance_criteria', description: 'At least 3 descriptions must have a written comment.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Quality Rating (1–5)', type: 'rating', options: ['1','2','3','4','5'], required: true },
      { id: 'f2', label: 'Issues Found', type: 'checkbox', options: ['Factual error', 'Grammar issue', 'Tone mismatch', 'Misleading claim', 'None'], required: true },
      { id: 'f3', label: 'Improvement Suggestion', type: 'textarea', required: false, placeholder: 'How could this description be improved?' },
    ],
    createdAt: '2026-09-30T10:00:00Z',
  },
  {
    id: 'task-006',
    title: 'Research Data Collection',
    category: 'research',
    shortDescription: 'Collect structured market data from public sources.',
    description: 'Research and document pricing data for 10 specified software products from their public pricing pages. Record the plan name, price, included features, and last verified date. This supports competitive intelligence research.',
    reward: 60,
    estimatedMinutes: 15,
    difficulty: 'medium',
    slots: 60,
    remainingSlots: 28,
    qualityScore: 94,
    status: 'active',
    businessId: 'biz-nova-labs',
    businessName: 'Nova Labs',
    tags: ['research', 'market data', 'pricing'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Only use official company websites as sources.' },
      { id: 'r2', type: 'acceptance_criteria', description: 'All 10 products must be documented.' },
      { id: 'r3', type: 'acceptance_criteria', description: 'Prices must include currency symbol and billing period.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Product Name', type: 'text', required: true, placeholder: 'e.g. Notion' },
      { id: 'f2', label: 'Plan & Price', type: 'textarea', required: true, placeholder: 'e.g. Pro: $16/month, Team: $20/month...' },
      { id: 'f3', label: 'Data Source URL', type: 'text', required: true, placeholder: 'https://...' },
    ],
    createdAt: '2026-10-01T13:00:00Z',
  },
  {
    id: 'task-007',
    title: 'App Onboarding Flow Testing',
    category: 'testing',
    shortDescription: 'Test the onboarding experience of a mobile app and report friction.',
    description: 'Download and run through the onboarding flow of our new mobile productivity app. Complete registration, connect at least one integration, and set a goal. Document any confusing steps, errors, or points where you wanted to quit.',
    reward: 80,
    estimatedMinutes: 20,
    difficulty: 'hard',
    slots: 40,
    remainingSlots: 15,
    qualityScore: 98,
    status: 'active',
    businessId: 'biz-datanest',
    businessName: 'DataNest',
    tags: ['testing', 'mobile', 'onboarding'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Use an Android device (Android 10 or higher).' },
      { id: 'r2', type: 'acceptance_criteria', description: 'Must complete at least 3 onboarding steps.' },
      { id: 'r3', type: 'acceptance_criteria', description: 'Feedback must reference specific UI elements or steps.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Steps Completed', type: 'radio', options: ['All steps', '5+ steps', '3–4 steps', 'Fewer than 3 steps'], required: true },
      { id: 'f2', label: 'Friction Points', type: 'textarea', required: true, placeholder: 'Where did you feel confused or frustrated?' },
      { id: 'f3', label: 'Overall Rating (1–5)', type: 'rating', options: ['1','2','3','4','5'], required: true },
    ],
    createdAt: '2026-10-02T09:30:00Z',
  },
  {
    id: 'task-008',
    title: 'Receipt Classification',
    category: 'data-labeling',
    shortDescription: 'Classify digital receipts into expense categories.',
    description: 'You will be shown images of digital receipts and invoices. Classify each into the correct expense category for financial reporting purposes. This data trains an automated expense classification model.',
    reward: 45,
    estimatedMinutes: 10,
    difficulty: 'easy',
    slots: 300,
    remainingSlots: 201,
    qualityScore: 97,
    status: 'active',
    businessId: 'biz-urban-research',
    businessName: 'Urban Research',
    tags: ['finance', 'classification', 'receipts'],
    requirements: [
      { id: 'r1', type: 'instruction', description: 'Select the most specific category available.' },
      { id: 'r2', type: 'acceptance_criteria', description: '9/10 must match the expected category.' },
    ],
    inputFields: [
      { id: 'f1', label: 'Expense Category', type: 'select', options: ['Travel', 'Meals & Entertainment', 'Office Supplies', 'Software/SaaS', 'Hardware', 'Utilities', 'Marketing', 'Professional Services', 'Other'], required: true },
      { id: 'f2', label: 'Confidence', type: 'radio', options: ['High', 'Medium', 'Low'], required: true },
    ],
    createdAt: '2026-10-03T11:00:00Z',
  },
];

// ============================
// Submissions
// ============================

export const SEED_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    taskId: 'task-001',
    taskTitle: 'Product Image Categorization',
    contributorId: 'user-contributor-demo',
    contributorName: 'Parth Sharma',
    contributorLevel: 4,
    data: { 'f1': 'Electronics', 'f2': 'High', 'f3': 'Clear product shot.' },
    status: 'rewarded',
    automatedChecks: [
      { id: 'ac1', label: 'Required fields complete', passed: true },
      { id: 'ac2', label: 'No duplicate detected', passed: true },
      { id: 'ac3', label: 'Format valid', passed: true },
      { id: 'ac4', label: 'Task constraints satisfied', passed: true },
    ],
    review: { reviewerId: 'user-business-demo', status: 'approved', feedback: 'Excellent accuracy.', reviewedAt: '2026-09-21T15:00:00Z' },
    reward: 50,
    transactionId: 'tx-001',
    submittedAt: '2026-09-21T12:00:00Z',
  },
  {
    id: 'sub-002',
    taskId: 'task-004',
    taskTitle: 'Survey on Student Tech Habits',
    contributorId: 'user-contributor-demo',
    contributorName: 'Parth Sharma',
    contributorLevel: 4,
    data: { 'f1': 'YouTube', 'f2': '6–10 hours', 'f3': 'Keeping focus and avoiding distractions remains my biggest challenge.', 'f4': 'An AI-powered study coach.' },
    status: 'rewarded',
    automatedChecks: [
      { id: 'ac1', label: 'Required fields complete', passed: true },
      { id: 'ac2', label: 'No duplicate detected', passed: true },
      { id: 'ac3', label: 'Format valid', passed: true },
      { id: 'ac4', label: 'Text length requirement met', passed: true },
    ],
    review: { reviewerId: 'user-business-demo', status: 'approved', reviewedAt: '2026-09-29T10:00:00Z' },
    reward: 20,
    transactionId: 'tx-002',
    submittedAt: '2026-09-28T18:00:00Z',
  },
  {
    id: 'sub-003',
    taskId: 'task-002',
    taskTitle: 'AI Response Evaluation',
    contributorId: 'user-contributor-demo',
    contributorName: 'Parth Sharma',
    contributorLevel: 4,
    data: { 'f1': 'Response A', 'f2': '4', 'f3': '5', 'f4': '3', 'f5': 'Response A was more factual but had a slightly formal tone.' },
    status: 'under_review',
    automatedChecks: [
      { id: 'ac1', label: 'Required fields complete', passed: true },
      { id: 'ac2', label: 'No duplicate detected', passed: true },
      { id: 'ac3', label: 'Format valid', passed: true },
      { id: 'ac4', label: 'Task constraints satisfied', passed: true },
    ],
    submittedAt: '2026-10-04T14:00:00Z',
  },
  {
    id: 'sub-004',
    taskId: 'task-005',
    taskTitle: 'Product Description Review',
    contributorId: 'user-contributor-demo',
    contributorName: 'Parth Sharma',
    contributorLevel: 4,
    data: { 'f1': '3', 'f2': ['Tone mismatch'], 'f3': 'The description uses overly casual language for a B2B product.' },
    status: 'rejected',
    automatedChecks: [
      { id: 'ac1', label: 'Required fields complete', passed: true },
      { id: 'ac2', label: 'No duplicate detected', passed: true },
      { id: 'ac3', label: 'Format valid', passed: true },
      { id: 'ac4', label: 'Minimum comments requirement', passed: false, detail: 'Only 1 of 3 required comments provided.' },
    ],
    review: { reviewerId: 'user-business-demo', status: 'rejected', feedback: 'At least 3 descriptions must have a written comment. Only 1 was provided.', reviewedAt: '2026-10-02T10:00:00Z' },
    submittedAt: '2026-10-01T20:00:00Z',
  },
  // Additional submissions for business to review
  {
    id: 'sub-005',
    taskId: 'task-001',
    taskTitle: 'Product Image Categorization',
    contributorId: 'contrib-002',
    contributorName: 'Aanya Kapoor',
    contributorLevel: 3,
    data: { 'f1': 'Electronics', 'f2': 'High', 'f3': '' },
    status: 'under_review',
    automatedChecks: [
      { id: 'ac1', label: 'Required fields complete', passed: true },
      { id: 'ac2', label: 'No duplicate detected', passed: true },
      { id: 'ac3', label: 'Format valid', passed: true },
      { id: 'ac4', label: 'Task constraints satisfied', passed: true },
    ],
    submittedAt: '2026-10-05T09:00:00Z',
  },
  {
    id: 'sub-006',
    taskId: 'task-002',
    taskTitle: 'AI Response Evaluation',
    contributorId: 'contrib-003',
    contributorName: 'Rohit Mehta',
    contributorLevel: 5,
    data: { 'f1': 'Response B', 'f2': '5', 'f3': '4', 'f4': '5', 'f5': 'Response B was clearer and more comprehensive.' },
    status: 'under_review',
    automatedChecks: [
      { id: 'ac1', label: 'Required fields complete', passed: true },
      { id: 'ac2', label: 'No duplicate detected', passed: true },
      { id: 'ac3', label: 'Format valid', passed: true },
      { id: 'ac4', label: 'Task constraints satisfied', passed: true },
    ],
    submittedAt: '2026-10-05T11:00:00Z',
  },
];

// ============================
// Wallet / Transactions
// ============================

export const DEMO_CONTRIBUTOR_WALLET: Wallet = {
  userId: 'user-contributor-demo',
  balance: 1250,
  reserved: 0,
  totalEarned: 1380,
  totalSpent: 130,
  address: '0xA3f8b2C1e4D5...3D2c',
  transactions: [
    {
      id: 'tx-001',
      type: 'task_reward',
      amount: 50,
      direction: 'credit',
      label: 'Task Reward',
      taskId: 'task-001',
      taskTitle: 'Product Image Categorization',
      submissionId: 'sub-001',
      status: 'confirmed',
      proofHash: '0x7f3a...9b12',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-21T15:30:00Z',
    },
    {
      id: 'tx-002',
      type: 'task_reward',
      amount: 20,
      direction: 'credit',
      label: 'Task Reward',
      taskId: 'task-004',
      taskTitle: 'Survey on Student Tech Habits',
      submissionId: 'sub-002',
      status: 'confirmed',
      proofHash: '0x2c8d...4f91',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-29T10:15:00Z',
    },
    {
      id: 'tx-003',
      type: 'task_reward',
      amount: 70,
      direction: 'credit',
      label: 'Task Reward',
      taskTitle: 'Website UX Testing',
      status: 'confirmed',
      proofHash: '0xa1b2...c3d4',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-18T16:00:00Z',
    },
    {
      id: 'tx-004',
      type: 'task_reward',
      amount: 35,
      direction: 'credit',
      label: 'Task Reward',
      taskTitle: 'AI Response Evaluation',
      status: 'confirmed',
      proofHash: '0xe5f6...a7b8',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-15T14:00:00Z',
    },
    {
      id: 'tx-005',
      type: 'task_reward',
      amount: 40,
      direction: 'credit',
      label: 'Task Reward',
      taskTitle: 'Content Quality Review',
      status: 'confirmed',
      proofHash: '0xc9d0...e1f2',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-10T11:00:00Z',
    },
  ],
};

export const DEMO_BUSINESS_WALLET: Wallet = {
  userId: 'user-business-demo',
  balance: 6550,
  reserved: 2400,
  totalEarned: 0,
  totalSpent: 8450,
  address: '0xB7c9...F4a1',
  transactions: [
    {
      id: 'btx-001',
      type: 'task_funding',
      amount: 5000,
      direction: 'debit',
      label: 'Task Budget Funded',
      taskId: 'task-001',
      taskTitle: 'Product Image Categorization',
      status: 'confirmed',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-20T09:00:00Z',
    },
    {
      id: 'btx-002',
      type: 'task_reward',
      amount: 50,
      direction: 'debit',
      label: 'Reward Released',
      taskId: 'task-001',
      submissionId: 'sub-001',
      status: 'confirmed',
      proofHash: '0x7f3a...9b12',
      network: 'TaskProof Local Network',
      timestamp: '2026-09-21T15:30:00Z',
    },
  ],
};

// ============================
// Leaderboard
// ============================

export const SEED_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, userId: 'lb-1', name: 'Vikram Rao', level: 5, levelName: 'Verified Specialist', tasksCompleted: 127, qualityScore: 99, totalEarned: 5840 },
  { rank: 2, userId: 'lb-2', name: 'Shreya Nair', level: 5, levelName: 'Verified Specialist', tasksCompleted: 112, qualityScore: 98, totalEarned: 5120 },
  { rank: 3, userId: 'lb-3', name: 'Ankit Joshi', level: 4, levelName: 'Data Explorer', tasksCompleted: 96, qualityScore: 97, totalEarned: 4200 },
  { rank: 4, userId: 'user-contributor-demo', name: 'Parth Sharma', level: 4, levelName: 'Data Explorer', tasksCompleted: 48, qualityScore: 96, totalEarned: 1250, isCurrentUser: true },
  { rank: 5, userId: 'lb-5', name: 'Priya Menon', level: 3, levelName: 'Task Explorer', tasksCompleted: 41, qualityScore: 95, totalEarned: 1100 },
  { rank: 6, userId: 'lb-6', name: 'Karan Singh', level: 3, levelName: 'Task Explorer', tasksCompleted: 38, qualityScore: 94, totalEarned: 980 },
  { rank: 7, userId: 'lb-7', name: 'Divya Shah', level: 3, levelName: 'Task Explorer', tasksCompleted: 34, qualityScore: 93, totalEarned: 870 },
  { rank: 8, userId: 'lb-8', name: 'Rahul Gupta', level: 2, levelName: 'Contributor', tasksCompleted: 28, qualityScore: 92, totalEarned: 720 },
  { rank: 9, userId: 'lb-9', name: 'Meera Pillai', level: 2, levelName: 'Contributor', tasksCompleted: 22, qualityScore: 91, totalEarned: 580 },
  { rank: 10, userId: 'lb-10', name: 'Arjun Desai', level: 2, levelName: 'Contributor', tasksCompleted: 19, qualityScore: 90, totalEarned: 490 },
];

// ============================
// Notifications
// ============================

export const SEED_NOTIFICATIONS: Notification[] = [
  { id: 'n1', userId: 'user-contributor-demo', title: 'Task Approved!', body: 'Your Product Image Categorization submission has been approved. +50 TCR added.', type: 'reward', read: false, createdAt: '2026-09-21T15:30:00Z' },
  { id: 'n2', userId: 'user-contributor-demo', title: 'Submission Under Review', body: 'Your AI Response Evaluation submission is now under business review.', type: 'review', read: true, createdAt: '2026-10-04T14:05:00Z' },
  { id: 'n3', userId: 'user-contributor-demo', title: 'Task Rejected', body: 'Your Product Description Review submission was rejected. See feedback.', type: 'review', read: true, createdAt: '2026-10-02T10:00:00Z' },
];

// ============================
// Business Analytics
// ============================

export const DEMO_BUSINESS_ANALYTICS: BusinessAnalytics = {
  tasksCreated: 12,
  totalSubmissions: 248,
  approved: 195,
  rejected: 23,
  underReview: 30,
  completionRate: 82,
  approvalRate: 87,
  avgReviewTimeHours: 4.2,
  avgReward: 48,
  totalSpent: 8450,
  qualityScore: 94,
  submissionsOverTime: [
    { date: 'Sep 25', count: 18 },
    { date: 'Sep 26', count: 24 },
    { date: 'Sep 27', count: 31 },
    { date: 'Sep 28', count: 22 },
    { date: 'Sep 29', count: 28 },
    { date: 'Sep 30', count: 35 },
    { date: 'Oct 1', count: 29 },
    { date: 'Oct 2', count: 38 },
    { date: 'Oct 3', count: 42 },
    { date: 'Oct 4', count: 33 },
    { date: 'Oct 5', count: 26 },
  ],
  approvalRateOverTime: [
    { date: 'Sep 25', rate: 82 },
    { date: 'Sep 26', rate: 85 },
    { date: 'Sep 27', rate: 83 },
    { date: 'Sep 28', rate: 88 },
    { date: 'Sep 29', rate: 87 },
    { date: 'Sep 30', rate: 90 },
    { date: 'Oct 1', rate: 86 },
    { date: 'Oct 2', rate: 89 },
    { date: 'Oct 3', rate: 91 },
    { date: 'Oct 4', rate: 88 },
    { date: 'Oct 5', rate: 87 },
  ],
};

// ============================
// Level definitions
// ============================

export const LEVELS = [
  { level: 1, name: 'Newcomer', minXp: 0, maxXp: 200 },
  { level: 2, name: 'Contributor', minXp: 200, maxXp: 600 },
  { level: 3, name: 'Task Explorer', minXp: 600, maxXp: 1200 },
  { level: 4, name: 'Data Explorer', minXp: 1200, maxXp: 3000 },
  { level: 5, name: 'Verified Specialist', minXp: 3000, maxXp: 9999 },
];
